name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome]

    services:
      selenium:
        image: selenium/standalone-${{ matrix.browser }}:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size 2g

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Maven dependencies
      run: mvn dependency:go-offline

    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -N https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/local/bin/

    - name: Run tests with Maven
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
      run: mvn test

    - name: Generate Allure Report
      run: |
        mvn allure:report
        mvn allure:serve

    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: target/site/allure-maven-plugin

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports
