name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Maven dependencies
      run: mvn dependency:go-offline

    - name: Install ChromeDriver
      run: |
        Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip -OutFile chromedriver_win32.zip
        Expand-Archive -Path chromedriver_win32.zip -DestinationPath C:\Users\runneradmin\AppData\Local\Temp\chdriver
        Copy-Item -Path C:\Users\runneradmin\AppData\Local\Temp\chdriver\chromedriver.exe -Destination C:\Windows\System32

    - name: Set up Chrome
      run: |
        choco install googlechrome --version=114.0.5735.90
      shell: powershell

    - name: Run tests with Maven
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
      run: mvn test

    - name: Generate Allure Report
      run: |
        mvn allure:report
        mvn allure:serve

    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: target/site/allure-maven-plugin

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports
