name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Maven dependencies
      run: mvn dependency:go-offline

    - name: Install ChromeDriver
      run: |
        curl -o chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver.zip
        sudo mv chromedriver /usr/local/bin/
        rm chromedriver.zip

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run tests with Maven
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
      run: mvn test
      continue-on-error: true

    - name: Generate Allure Report
      run: |
        if [ -d "target/surefire-reports" ]; then
          mvn allure:report
        else
          echo "No test results found in target/surefire-reports, skipping Allure report generation."
        fi

    - name: Upload Allure Report
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: target/allure-report

    - name: Deploy Allure Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/allure-report
        destination_dir: allure-report
