name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Maven dependencies
      run: mvn dependency:go-offline

    - name: Install ChromeDriver
      run: |
        Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip -OutFile chromedriver_win32.zip
        Expand-Archive -Path chromedriver_win32.zip -DestinationPath C:\Windows\System32
      shell: powershell

    - name: Install Google Chrome
      run: |
        Invoke-WebRequest -Uri https://dl.google.com/chrome/install/latest/chrome_installer.exe -OutFile chrome_installer.exe
        Start-Process -FilePath chrome_installer.exe -Args "/silent /install" -NoNewWindow -Wait
      shell: powershell

    - name: Run tests with Maven
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
      run: mvn test
      continue-on-error: true

    - name: Print Maven test results if exist
      run: |
        if (Test-Path -Path target/surefire-reports) {
          Get-ChildItem -Path target/surefire-reports/*.txt | ForEach-Object { Get-Content $_.FullName }
        } else {
          Write-Output "No test results found in target/surefire-reports."
        }
      shell: powershell

    - name: Generate Allure Report
      run: |
        if (Test-Path -Path target/surefire-reports) {
          mvn allure:report
          Start-Process -FilePath "mvn" -ArgumentList "allure:serve" -NoNewWindow -Wait
          Start-Sleep -Seconds 30
          Stop-Process -Name "java" -Force
        } else {
          Write-Output "No test results found in target/surefire-reports, skipping Allure report generation."
        }
      shell: powershell

    - name: Upload Allure Report
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: target/site/allure-maven-plugin

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports
